const KEYS={players:'ballHandlers.players',game:'ballHandlers.game',presets:'ballHandlers.presets'};
const ratingNames=['Shooting','Ball handling','Passing','Rebounding','Defense','Speed','Stamina'];
const tagOptions={
 'Shooter':{shoot:1.2},'Corner shooter':{shoot:.8},'Playmaker':{handle:.7,pass:1.1},'Slasher':{handle:.5,speed:.6},'Finisher':{shoot:.4},'Screen setter':{rebound:.25},'Rim protector':{defense:1.1,rebound:.4},'Rebounder':{rebound:1.1},'Lockdown defender':{defense:1.2},'On-ball defender':{defense:.8},'Quick guard':{speed:.8,handle:.3},'Versatile defender':{defense:.8},'High motor':{stamina:.8},'Floor spacer':{shoot:1},'Post scorer':{shoot:.4,rebound:.4},'Transition runner':{speed:1,stamina:.4},'Turnover-prone':{handle:-.8,pass:-.5},'Defensive effort concern':{defense:-1.1}
};
const defaultPlayers=[
 {id:'jordan',name:'Jordan Lee',number:3,positions:['PG','SG'],tags:'Playmaker, on-ball defense',ratings:[3,5,4,2,4,4,4]},
 {id:'maya',name:'Maya Chen',number:7,positions:['SG','SF'],tags:'Catch-and-shoot, hustles',ratings:[5,3,3,2,3,4,4]},
 {id:'andre',name:'Andre Silva',number:11,positions:['SF','PF'],tags:'Slasher, rebounder',ratings:[3,3,3,4,3,4,4]},
 {id:'sam',name:'Sam Patel',number:22,positions:['PF','C'],tags:'Screen setter, rim protector',ratings:[2,2,3,4,5,2,4]},
 {id:'taylor',name:'Taylor Brooks',number:34,positions:['C'],tags:'Rebounding, interior defense',ratings:[2,1,2,5,4,2,4]},
 {id:'nico',name:'Nico Grant',number:14,positions:['SG','PG'],tags:'Scoring spark, quick guard',ratings:[4,4,2,2,2,5,3]}
];
let players=JSON.parse(localStorage.getItem(KEYS.players)||'null')||defaultPlayers;
const starterTags={jordan:['Playmaker','On-ball defender'],maya:['Shooter','Corner shooter'],andre:['Slasher','Rebounder'],sam:['Screen setter','Rim protector'],taylor:['Rebounder','Rim protector'],nico:['Shooter','Quick guard']};
players=players.map(p=>({...p,height:p.height||'',profileTags:p.profileTags?.length?p.profileTags:(starterTags[p.id]||[]),notes:p.notes||p.tags||''}));
let game=JSON.parse(localStorage.getItem(KEYS.game)||'null')||{date:'',available:Object.fromEntries(players.map(p=>[p.id,true])),selected:players.slice(0,6).map(p=>p.id),locked:[],offense:'balanced',defense:'man',priority:'fair'};
game.locked=game.locked||[];
let presets=JSON.parse(localStorage.getItem(KEYS.presets)||'[]');
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(KEYS.players,JSON.stringify(players));localStorage.setItem(KEYS.game,JSON.stringify(game));localStorage.setItem(KEYS.presets,JSON.stringify(presets));$('#save-status').textContent='Saved locally';setTimeout(()=>$('#save-status').textContent='Saved locally',500)}
function overall(p){return Math.round(p.ratings.reduce((a,b)=>a+b,0)/p.ratings.length*20)}
function renderPlayers(){const body=$('#players-table');body.innerHTML=players.length?players.map(p=>`<tr><td><span class="player-number">#${p.number||'—'}</span><span class="player-name">${esc(p.name)}</span></td><td>${esc(p.height)||'—'}</td><td>${p.positions.join(' / ')||'—'}</td><td>${p.profileTags.map(esc).join(', ')||'—'}</td><td class="overall">${overall(p)}</td><td><button data-edit="${p.id}">Edit</button></td></tr>`).join(''):'<tr><td colspan="6">No players yet. Add your first Ball Handler.</td></tr>';$$('[data-edit]').forEach(b=>b.onclick=()=>openPlayer(b.dataset.edit))}
function renderGame(){let selected=game.selected.filter(id=>players.some(p=>p.id===id));game.selected=selected;game.locked=game.locked.filter(id=>selected.includes(id));let count=selected.length;$('#roster-count').textContent=`${count} / 10 selected`;$('#generate').disabled=count<5;$('#game-warning').textContent=count<5?'Select at least 5 players to create a plan.':count>10?'Choose no more than 10 players.':count===10?'10-player cap reached.':game.locked.length?'Locked starters will be kept in the generated five.':'Ready to generate a plan.';$('#game-roster').innerHTML=players.map(p=>{let available=game.available[p.id]!==false, picked=selected.includes(p.id),locked=game.locked.includes(p.id);return `<article class="game-player"><div class="game-player-top"><div><span class="player-name">#${p.number||'—'} ${esc(p.name)}</span><small>${p.positions.join(' / ')||'No position'} · ${p.profileTags.map(esc).join(', ')||'No profile tags yet'}</small></div><b>${overall(p)}</b></div><div class="toggle-row"><label><input data-available="${p.id}" type="checkbox" ${available?'checked':''}/> Available</label><label><input data-select="${p.id}" type="checkbox" ${available&&picked?'checked':''} ${available?'':'disabled'}/> Bring</label>${available&&picked?`<label><input data-lock="${p.id}" type="checkbox" ${locked?'checked':''} ${!locked&&game.locked.length>=5?'disabled':''}/> Lock starter</label>`:''}</div></article>`}).join('');$$('[data-available]').forEach(i=>i.onchange=()=>{game.available[i.dataset.available]=i.checked;if(!i.checked){game.selected=game.selected.filter(id=>id!==i.dataset.available);game.locked=game.locked.filter(id=>id!==i.dataset.available)}save();renderGame()});$$('[data-select]').forEach(i=>i.onchange=()=>{if(i.checked&&game.selected.length>=10){i.checked=false;alert('You can bring up to 10 players.');return}game.selected=i.checked?[...game.selected,i.dataset.select]:game.selected.filter(id=>id!==i.dataset.select);if(!i.checked)game.locked=game.locked.filter(id=>id!==i.dataset.select);save();renderGame()});$$('[data-lock]').forEach(i=>i.onchange=()=>{game.locked=i.checked?[...game.locked,i.dataset.lock]:game.locked.filter(id=>id!==i.dataset.lock);save();renderGame()})}
function esc(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function setupRatings(values=[3,3,3,3,3,3,3]){$('#ratings').innerHTML='';ratingNames.forEach((name,i)=>{let node=$('#rating-template').content.firstElementChild.cloneNode(true);node.querySelector('span').textContent=name;let input=node.querySelector('input'),out=node.querySelector('output');input.value=values[i];out.textContent=values[i];input.oninput=()=>out.textContent=input.value;$('#ratings').append(node)})}
function setupTags(values=[]){$('#tag-chips').innerHTML=Object.keys(tagOptions).map(tag=>`<label><input type="checkbox" name="profile-tag" value="${tag}" ${values.includes(tag)?'checked':''}/> ${tag}</label>`).join('')}
function openPlayer(id){let p=players.find(x=>x.id===id);$('#dialog-heading').textContent=p?'Edit player':'Add player';$('#edit-id').value=p?.id||'';$('#name').value=p?.name||'';$('#number').value=p?.number??'';$('#height').value=p?.height||'';$('#notes').value=p?.notes||'';$$('[name=position]').forEach(c=>c.checked=p?.positions.includes(c.value)||false);setupRatings(p?.ratings);setupTags(p?.profileTags);$('#delete-player').style.display=p?'block':'none';$('#player-dialog').showModal()}
$('#new-player').onclick=()=>openPlayer();$('#close-dialog').onclick=$('#cancel-dialog').onclick=()=>$('#player-dialog').close();
$('#player-form').onsubmit=e=>{e.preventDefault();let id=$('#edit-id').value||crypto.randomUUID(),name=$('#name').value.trim(),p={id,name,number:$('#number').value?+$('#number').value:'',height:$('#height').value.trim(),positions:$$('[name=position]:checked').map(x=>x.value),profileTags:$$('[name=profile-tag]:checked').map(x=>x.value),notes:$('#notes').value.trim(),ratings:$$('#ratings input').map(i=>+i.value)};if(!p.positions.length){alert('Choose at least one position.');return}let old=players.findIndex(x=>x.id===id);if(old>=0)players[old]=p;else{players.push(p);game.available[id]=true}save();renderPlayers();renderGame();$('#player-dialog').close()};
$('#delete-player').onclick=()=>{let id=$('#edit-id').value;if(confirm('Delete this player profile?')){players=players.filter(p=>p.id!==id);game.selected=game.selected.filter(x=>x!==id);delete game.available[id];save();renderPlayers();renderGame();$('#player-dialog').close()}};
function tacticWeights(){let o=game.offense,d=game.defense;return {shoot:o==='spacing'?1.8:o==='bigs'?.6:o==='transition'?.8:1,handle:o==='movement'?1.35:o==='transition'?1.2:1,pass:o==='movement'?1.6:1,rebound:o==='bigs'?1.6:1,defense:d==='zone'?.9:1,speed:(o==='transition'||d==='perimeter')?1.4:1,inside:(d==='paint'||o==='bigs')?1.55:1}}
function combo(arr,n,start=0,chosen=[],out=[]){if(chosen.length===n){out.push(chosen);return out}for(let i=start;i<=arr.length-(n-chosen.length);i++)combo(arr,n,i+1,[...chosen,arr[i]],out);return out}
function heightInches(height){let m=String(height||'').match(/(\d+)\s*['′]\s*(\d{0,2})/);return m?+m[1]*12 + +(m[2]||0):0}
function score(lineup){let w=tacticWeights(), sums=lineup.reduce((a,p)=>p.ratings.map((v,i)=>(a[i]||0)+v),[]),pos=lineup.flatMap(p=>p.positions), guards=lineup.filter(p=>p.positions.some(x=>['PG','SG'].includes(x))).length,bigs=lineup.filter(p=>p.positions.some(x=>['PF','C'].includes(x))).length;let tagBonus=lineup.reduce((total,p)=>total+p.profileTags.reduce((sum,tag)=>{let t=tagOptions[tag]||{};return sum+(t.shoot||0)*w.shoot+(t.handle||0)*w.handle+(t.pass||0)*w.pass+(t.rebound||0)*w.rebound+(t.defense||0)*w.defense+(t.speed||0)*w.speed+(t.stamina||0)*.5},0),0);let heightBonus=lineup.reduce((sum,p)=>sum+Math.max(0,heightInches(p.height)-66)*.08*w.inside,0);let s=sums[0]*w.shoot+sums[1]*w.handle+sums[2]*w.pass+sums[3]*w.rebound+sums[4]*w.defense+sums[5]*w.speed+sums[6]*.5+tagBonus+heightBonus; if(guards<1)s-=18;if(bigs<1)s-=12;if(!pos.includes('PG'))s-=5;if(!pos.includes('C'))s-=3;return s}
function bestLineup(pool,needs={}){let all=combo(pool,5), priority=game.priority;if(game.locked.length===5&&Object.keys(needs).length===0)all=all.filter(line=>game.locked.every(id=>line.some(p=>p.id===id)));else if(game.locked.length&&Object.keys(needs).length===0)all=all.filter(line=>game.locked.every(id=>line.some(p=>p.id===id)));return all.sort((a,b)=>{let bonus=line=>line.reduce((x,p)=>x+(needs[p.id]||0)*(priority==='fair'?3:priority==='balanced'?1.2:.2),0);return score(b)+bonus(b)-score(a)-bonus(a)})[0]}
function court(line){let spots=[[50,81],[22,58],[78,58],[35,27],[65,27]];return `<section class="plan-card"><h3>Starting five on court</h3><p class="note">Static half-court view. The arrow shows a simple spacing lane, not a full play call.</p><div class="court"><span class="court-label">OFFENSE → BASKET</span>${line.map((p,i)=>`<span class="court-player" style="left:${spots[i][0]}%;top:${spots[i][1]}%">${esc(p.name.split(' ')[0].slice(0,5))}<small>${p.positions[0]}</small></span>`).join('')}<span class="motion-arrow" style="left:47%;top:51%">↑</span></div><p class="motion-key">For motion offense, keep the middle open: pass, cut, replace the empty spot.</p></section>`}
function plan(){let pool=players.filter(p=>game.selected.includes(p.id));if(pool.length<5)return;let starter=bestLineup(pool);let minutes=Object.fromEntries(pool.map(p=>[p.id,0]));let shifts=[];for(let i=0;i<8;i++){let needs=Object.fromEntries(pool.map(p=>[p.id,Math.max(0,20-minutes[p.id]) / 5]));let line=i===0?starter:bestLineup(pool,needs);line.forEach(p=>minutes[p.id]+=5);shifts.push(line)}let metrics=[['Ball handling',starter.reduce((a,p)=>a+p.ratings[1],0)],['Spacing',starter.reduce((a,p)=>a+p.ratings[0],0)],['Rebounding',starter.reduce((a,p)=>a+p.ratings[3],0)],['Defense',starter.reduce((a,p)=>a+p.ratings[4],0)]];let tacticText=`${$('#offense').selectedOptions[0].text} offense · ${$('#defense').selectedOptions[0].text} defense · ${$('#priority').selectedOptions[0].text}`;$('#plan-summary').textContent=`${pool.length} players selected · ${tacticText}`;$('#plan-output').className='plan-grid';$('#plan-output').innerHTML=`<section class="plan-card"><h3>What this plan emphasizes</h3><p>${explain(starter)}</p><p class="note">Profile tags affect the score; coach notes are for context only.</p></section><section class="plan-card"><h3>Suggested starting five</h3><p class="note">Designed for balance with your selected tactics.</p><div class="lineup">${starter.map(p=>`<div class="slot"><small>${p.positions[0]} · ${esc(p.height||'height not set')}</small><span>${esc(p.name.split(' ')[0])}</span><small>${esc(p.profileTags[0]||'')}</small></div>`).join('')}</div>${metrics.map(([name,value])=>`<div class="metric"><span>${name}</span><div class="meter"><i style="width:${Math.min(100,value*4)}%"></i></div><b>${value}</b></div>`).join('')}<p class="note">This five scores ${Math.round(score(starter))} for your current priorities.</p></section>${court(starter)}<section class="plan-card"><h3>Eight 5-minute shifts</h3><p class="note">Two halves · 20 minutes each</p><div class="shift-list">${shifts.map((line,i)=>`<div class="shift"><time>${i*5}–${i*5+5}</time><p>${line.map(p=>esc(p.name.split(' ')[0])).join(' · ')}</p></div>`).join('')}</div></section><section class="plan-card"><h3>Minute targets</h3><p class="note">Fair mode aims for 20 minutes each across the 40-minute game.</p><table class="minutes">${pool.map(p=>`<tr><td>${esc(p.name)}</td><td>${minutes[p.id]} min</td></tr>`).join('')}</table></section>`;$('.tab[data-tab="plan"]').click()}
function explain(line){let r=line.reduce((a,p)=>p.ratings.map((v,i)=>(a[i]||0)+v),[]), high=[['shooting and floor spacing',r[0]],['ball handling and creation',r[1]+r[2]],['rebounding',r[3]],['defense',r[4]]].sort((a,b)=>b[1]-a[1])[0][0];return `This unit leans into ${high}. It includes ${line.filter(p=>p.positions.some(x=>['PG','SG'].includes(x))).length} guard-capable player${line.filter(p=>p.positions.some(x=>['PG','SG'].includes(x))).length===1?'':'s'} and ${line.filter(p=>p.positions.some(x=>['PF','C'].includes(x))).length} big-capable player${line.filter(p=>p.positions.some(x=>['PF','C'].includes(x))).length===1?'':'s'}.`}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
['offense','defense','priority'].forEach(id=>$('#'+id).onchange=e=>{game[id]=e.target.value;save()});$('#game-date').value=game.date;$('#game-date').onchange=e=>{game.date=e.target.value;save()};$('#generate').onclick=plan;$('#regenerate').onclick=plan;
$('#offense').value=game.offense;$('#defense').value=game.defense;$('#priority').value=game.priority;renderPlayers();renderGame();save();
$('#export-roster').onclick=()=>{let blob=new Blob([JSON.stringify({team:'The Ball Handlers',players},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='the-ball-handlers-roster.json';a.click();URL.revokeObjectURL(url)};
$('#import-roster').onchange=e=>{let file=e.target.files[0];if(!file)return;let reader=new FileReader();reader.onload=()=>{try{let data=JSON.parse(reader.result),incoming=Array.isArray(data)?data:data.players;if(!Array.isArray(incoming)||!incoming.every(p=>p.id&&p.name&&Array.isArray(p.ratings)))throw Error();if(!confirm('Replace the current player pool with this imported roster?'))return;players=incoming.map(p=>({...p,height:p.height||'',profileTags:p.profileTags||[],notes:p.notes||''}));game.available=Object.fromEntries(players.map(p=>[p.id,true]));game.selected=[];save();renderPlayers();renderGame();alert('Roster imported. Set availability for the next game.')}catch{alert('That file is not a valid Ball Handlers roster export.')}};reader.readAsText(file);e.target.value=''};
function renderPresets(){let select=$('#preset-list');select.innerHTML='<option value="">Saved lineups</option>'+presets.map((p,i)=>`<option value="${i}">${esc(p.name)}</option>`).join('')}
$('#save-preset').onclick=()=>{if(game.locked.length!==5){alert('Lock exactly five starters on Game night, then save them as a lineup.');return}let name=prompt('Name this five-player lineup:');if(!name?.trim())return;presets.push({name:name.trim(),ids:[...game.locked]});save();renderPresets();$('#preset-list').value=String(presets.length-1)};
$('#load-preset').onclick=()=>{let preset=presets[+$('#preset-list').value];if(!preset){alert('Choose a saved lineup first.');return}if(!preset.ids.every(id=>game.selected.includes(id))){alert('All five saved players need to be selected for this game first.');return}game.locked=[...preset.ids];save();renderGame();$('.tab[data-tab="game"]').click()};
renderPresets();
