'use client';

import { ChangeEvent, useEffect, useMemo, useState } from 'react';
import { createRotation, evaluate, recommend, roleLabel, suggestedRoles, suggestArchetype } from '../lib/lineup';
import { exportStore, loadStore, parseImport, persist } from '../lib/storage';
import { defaultGame, emptyRatings, POSITIONS, ROLES, type Player, type Priority, type Ratings, type Role, type Store } from '../lib/types';

type Tab = 'roster' | 'game' | 'lineups' | 'plans';
const bands = [
  ['shooting', 'Shooting & spacing', 'green', [['shooting', 'Shooting'], ['spacing', 'Off-ball spacing']]],
  ['playmaking', 'Playmaking', 'yellow', [['handle', 'Ball handling'], ['passing', 'Passing'], ['decisions', 'Decision making']]],
  ['finishing', 'Finishing & rim pressure', 'blue', [['rimPressure', 'Rim pressure'], ['finishing', 'Finishing']]],
  ['defense', 'Defense', 'red', [['poa', 'Point of attack'], ['help', 'Help defense'], ['rimProtection', 'Rim protection']]],
  ['physical', 'Physical & rebounding', 'slate', [['rebounding', 'Rebounding'], ['size', 'Size / strength'], ['mobility', 'Mobility'], ['stamina', 'Stamina']]],
] as const;
const ratingWords: Record<number, string> = { 1: 'Major weakness', 2: 'Major weakness', 3: 'Limited', 4: 'Limited', 5: 'Capable', 6: 'Capable', 7: 'Strong', 8: 'Strong', 9: 'Elite', 10: 'Defining strength' };
const newPlayer = (): Player => { const now = new Date().toISOString(), ratings = emptyRatings(); return { id: crypto.randomUUID(), name: '', positions: [], ratings, roles: suggestedRoles(ratings), archetype: suggestArchetype(ratings), coachNotes: '', createdAt: now, updatedAt: now }; };
const copy = <T,>(value: T): T => JSON.parse(JSON.stringify(value));

function initials(name: string) { return name.trim().split(/\s+/).map(v => v[0]).join('').slice(0, 2).toUpperCase() || '•'; }
function PlayerAvatar({ player }: { player: Player }) { return <span className="avatar">{initials(player.name)}</span>; }
function Chip({ active, onClick, children, tone = '' }: { active?: boolean; onClick?: () => void; children: React.ReactNode; tone?: string }) { return <button type="button" onClick={onClick} className={`chip ${active ? 'active' : ''} ${tone}`}>{children}</button>; }

export default function Home() {
  const [store, setStore] = useState<Store>(() => ({ version: 2, players: [], game: defaultGame(), presets: [], plans: [] }));
  const [hydrated, setHydrated] = useState(false); const [tab, setTab] = useState<Tab>('roster');
  const [draft, setDraft] = useState<Player | null>(null); const [notice, setNotice] = useState('');
  const [saveDialog, setSaveDialog] = useState<'preset' | 'plan' | null>(null); const [saveName, setSaveName] = useState('');
  useEffect(() => { setStore(loadStore()); setHydrated(true); }, []);
  useEffect(() => { if (hydrated) persist(store); }, [store, hydrated]);
  const update = (fn: (old: Store) => Store) => setStore(old => fn(copy(old)));
  const pool = useMemo(() => store.players.filter(p => store.game.selectedIds.includes(p.id)), [store]);
  const starter = useMemo(() => pool.length >= 5 ? recommend(pool, store.game) : undefined, [pool, store.game]);
  const rotation = useMemo(() => pool.length >= 5 ? createRotation(pool, store.game) : undefined, [pool, store.game]);
  const selected = store.game.selectedIds;
  function savePlayer() { if (!draft?.name.trim() || !draft.positions.length) { setNotice('Give the player a name and at least one position.'); return; } update(s => ({ ...s, players: s.players.some(p => p.id === draft.id) ? s.players.map(p => p.id === draft.id ? { ...draft, updatedAt: new Date().toISOString() } : p) : [...s.players, { ...draft, updatedAt: new Date().toISOString() }] })); setDraft(null); setNotice('Player profile saved locally.'); }
  function removePlayer(id: string) { if (!confirm('Delete this player profile?')) return; update(s => ({ ...s, players: s.players.filter(p => p.id !== id), game: { ...s.game, selectedIds: s.game.selectedIds.filter(x => x !== id), starterLocks: s.game.starterLocks.filter(x => x !== id) }, presets: s.presets.filter(p => !p.playerIds.includes(id)) })); setNotice('Player removed.'); }
  function toggleSelect(id: string) { update(s => { const inGame = s.game.selectedIds.includes(id); if (!inGame && s.game.selectedIds.length >= 10) { setNotice('A game roster can include up to 10 players.'); return s; } const selectedIds = inGame ? s.game.selectedIds.filter(x => x !== id) : [...s.game.selectedIds, id]; return { ...s, game: { ...s.game, selectedIds, starterLocks: s.game.starterLocks.filter(x => selectedIds.includes(x)) } }; }); }
  function toggleLock(id: string) { update(s => { const locks = s.game.starterLocks.includes(id) ? s.game.starterLocks.filter(x => x !== id) : s.game.starterLocks.length < 5 ? [...s.game.starterLocks, id] : s.game.starterLocks; if (locks.length === s.game.starterLocks.length && !s.game.starterLocks.includes(id)) setNotice('You can lock up to five starters.'); return { ...s, game: { ...s.game, starterLocks: locks } }; }); }
  function download() { const blob = new Blob([exportStore(store)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'the-ball-handlers-v2-backup.json'; a.click(); URL.revokeObjectURL(url); }
  function importBackup(e: ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const imported = parseImport(String(reader.result)); if (!confirm('Replace this local roster, presets, and saved plans?')) return; setStore(imported); setNotice('Backup imported.'); } catch (error) { setNotice(error instanceof Error ? error.message : 'Could not import that file.'); } }; reader.readAsText(file); e.target.value = ''; }
  function commitSave() { if (!saveName.trim() || !rotation) return; if (saveDialog === 'preset') { const ids = starter?.players.map(p => p.id) || []; if (ids.length !== 5) return; update(s => ({ ...s, presets: [...s.presets, { id: crypto.randomUUID(), name: saveName.trim(), playerIds: ids, createdAt: new Date().toISOString() }] })); setNotice('Five-player preset saved.'); }
    if (saveDialog === 'plan') update(s => ({ ...s, plans: [...s.plans, { id: crypto.randomUUID(), name: saveName.trim(), createdAt: new Date().toISOString(), settings: s.game, starterIds: rotation.starterIds, shifts: rotation.shifts, minuteTargets: rotation.minutes, algorithmVersion: 'v2.0' }] }));
    setSaveDialog(null); setSaveName('');
  }
  function loadPreset(ids: string[]) { update(s => ({ ...s, game: { ...s.game, selectedIds: Array.from(new Set([...s.game.selectedIds, ...ids])).slice(0, 10), starterLocks: ids } })); setTab('lineups'); setNotice('Preset loaded as starter locks.'); }
  return <main>
    <header className="hero"><div className="brand"><span className="brand-mark">BH</span><div><p className="eyebrow">REC BASKETBALL PLANNER</p><h1>The Ball Handlers</h1></div></div><div className="save-state"><span className="save-dot" /> {hydrated ? 'Saved on this device' : 'Loading workspace'}</div></header>
    <div className="shell"><nav className="nav" aria-label="Main navigation">{([['roster','Roster'],['game','Game night'],['lineups','Lineups'],['plans','Saved']] as [Tab,string][]).map(([id,label]) => <button key={id} className={tab === id ? 'nav-item active' : 'nav-item'} onClick={() => setTab(id)}>{label}{id === 'game' && selected.length ? <b>{selected.length}</b> : null}</button>)}</nav>
      {notice && <div className="toast" role="status">{notice}<button onClick={() => setNotice('')}>×</button></div>}
      {tab === 'roster' && <section className="page"><div className="section-head"><div><p className="eyebrow ink">TEAM POOL</p><h2>Build your roster</h2><p>Profiles are kept on this device and use a simple 1–10 scouting scale.</p></div><div className="head-actions"><label className="button secondary">Import roster / backup<input type="file" accept="application/json" onChange={importBackup} hidden /></label><button className="button secondary" onClick={download}>Export backup</button><button className="button primary" onClick={() => setDraft(newPlayer())}>+ Add player</button></div></div>
        {!store.players.length ? <div className="empty"><div className="empty-ball">◉</div><h3>Your roster is ready for its first player.</h3><p>Add a player, rate their on-court strengths, and the planner will suggest roles and archetypes.</p><button className="button primary" onClick={() => setDraft(newPlayer())}>Create first profile</button></div> : <div className="roster-grid">{store.players.map(p => <article className="player-card" key={p.id}><div className="card-top"><PlayerAvatar player={p}/><div><h3>{p.name}</h3><p>#{p.jerseyNumber || '—'} · {p.positions.join(' / ')}</p></div><button className="icon" aria-label={`Edit ${p.name}`} onClick={() => setDraft(copy(p))}>•••</button></div><div className="archetype">{p.archetype}</div><div className="mini-bars">{bands.map(([key,,tone]) => { const group = p.ratings[key as keyof Ratings] as Record<string,number>; const avg = Object.values(group).reduce((a,b) => a+b,0)/Object.values(group).length; return <span key={key}><i className={tone} style={{ width: `${avg * 10}%` }}/></span>; })}</div><div className="role-row">{p.roles.slice(0,3).map(r => <span key={r}>{roleLabel(r)}</span>)}{p.roles.length > 3 && <span>+{p.roles.length - 3}</span>}</div></article>)}</div>}
      </section>}
      {tab === 'game' && <section className="page"><div className="section-head"><div><p className="eyebrow ink">GAME SETUP</p><h2>Who&apos;s running today?</h2><p>Select up to ten available players, then set a simple game plan.</p></div><div className="count">{selected.length}<small>/ 10 players</small></div></div><div className="game-grid">{store.players.map(p => <button className={`pick-card ${selected.includes(p.id) ? 'chosen' : ''}`} key={p.id} onClick={() => toggleSelect(p.id)}><PlayerAvatar player={p}/><span><b>{p.name}</b><small>{p.positions.join(' / ')} · {p.archetype}</small></span><i>{selected.includes(p.id) ? '✓' : '+'}</i></button>)}</div>{!store.players.length && <div className="empty compact"><p>Add player profiles first, then assemble the game roster here.</p></div>}
        <div className="settings"><div><p className="eyebrow ink">COACHING SETTINGS</p><h3>How should this game feel?</h3></div><Setting label="Offense" value={store.game.offense} options={[['balanced','Balanced'],['spacing','Spacing'],['pace','Push pace'],['interior','Paint pressure'],['movement','Ball movement']]} onChange={v => update(s => ({...s,game:{...s.game,offense:v as any}}))}/><Setting label="Defense" value={store.game.defense} options={[['man','Man-to-man'],['zone','Zone'],['paint','Protect paint'],['perimeter','Pressure perimeter'],['switch','Switch more']]} onChange={v => update(s => ({...s,game:{...s.game,defense:v as any}}))}/><Setting label="Priority" value={store.game.priority} options={[['fair','Fair'],['balanced','Balanced'],['win','Best chance to win']]} onChange={v => update(s => ({...s,game:{...s.game,priority:v as Priority}}))}/></div>
        <div className="next-row"><span>{selected.length >= 5 ? 'Ready to build fit-first lineups.' : `Add ${5-selected.length} more player${5-selected.length === 1 ? '' : 's'} to create a lineup.`}</span><button className="button primary" disabled={selected.length < 5} onClick={() => setTab('lineups')}>Build lineups →</button></div>
      </section>}
      {tab === 'lineups' && <section className="page"><div className="section-head"><div><p className="eyebrow ink">FIT-FIRST LINEUPS</p><h2>Recommended starting five</h2><p>Elite skills, role coverage, tactics, and fair minutes—not a total-rating contest.</p></div><div className="head-actions"><button className="button secondary" disabled={!starter} onClick={() => { setSaveDialog('preset'); setSaveName(''); }}>Save five</button><button className="button primary" disabled={!rotation} onClick={() => { setSaveDialog('plan'); setSaveName(''); }}>Save game plan</button></div></div>
        {!starter ? <div className="empty"><h3>Select at least five players for game night.</h3><p>The planner needs a five-player pool before it can assess fit.</p><button className="button primary" onClick={() => setTab('game')}>Go to game night</button></div> : <><div className="lineup-layout"><section className="lineup-main"><div className="court-title"><div><p className="eyebrow ink">STARTING UNIT</p><h3>Best fit right now <span className="score">{Math.round(starter.score)}</span></h3></div><span className="priority-tag">{store.game.priority === 'win' ? 'Win now' : store.game.priority}</span></div><div className="court">{starter.players.map((p,i) => <div className={`court-player p${i+1}`} key={p.id}><PlayerAvatar player={p}/><b>{p.name.split(' ')[0]}</b><small>{p.positions[0]}</small></div>)}</div><div className="locks"><span>Manual starter locks</span><div>{pool.map(p => <Chip key={p.id} active={store.game.starterLocks.includes(p.id)} onClick={() => toggleLock(p.id)}>{store.game.starterLocks.includes(p.id) ? '✓ ' : ''}{p.name.split(' ')[0]}</Chip>)}</div></div></section><aside className="fit-panel"><h3>Why it fits</h3>{starter.reasons.map(x => <p className="reason" key={x}>{x}</p>)}<h4>Strengths</h4>{starter.strengths.map(x => <p className="positive" key={x}>↗ {x}</p>)}<h4>Risks to manage</h4>{starter.risks.length ? starter.risks.map(x => <p className="risk" key={x}>! {x}</p>) : <p className="positive">↗ No major fit risks detected.</p>}</aside></div><section className="metrics"><h3>Five-player fit profile</h3>{Object.entries(starter.metrics).map(([name,value]) => <div className="metric" key={name}><span>{name}</span><div><i style={{width:`${Math.min(100, value/38*100)}%`}}/></div><b>{Math.round(value)}</b></div>)}</section><section className="rotation"><div><p className="eyebrow ink">40-MINUTE ROTATION</p><h3>Eight five-minute shifts</h3><p>Fairness influences later shifts; starter locks apply only to the opening unit.</p></div><div className="shifts">{rotation?.shifts.map(s => <div className="shift" key={s.start}><time>{s.start}–{s.end}</time><span>{s.playerIds.map(id => store.players.find(p=>p.id===id)?.name.split(' ')[0]).join(' · ')}</span><small>{s.score}</small></div>)}</div><div className="minutes">{Object.entries(rotation?.minutes || {}).map(([id,min]) => <span key={id}><b>{store.players.find(p=>p.id===id)?.name.split(' ')[0]}</b> {min}m</span>)}</div></section></>}
      </section>}
      {tab === 'plans' && <section className="page"><div className="section-head"><div><p className="eyebrow ink">SAVED LOCALLY</p><h2>Your playbook</h2><p>Reusable five-player presets stay separate from complete game plans.</p></div></div><div className="saved-columns"><section className="saved-card"><h3>Lineup presets</h3>{store.presets.length ? store.presets.map(x => <div className="saved-item" key={x.id}><div><b>{x.name}</b><small>{x.playerIds.map(id => store.players.find(p => p.id === id)?.name || 'Missing player').join(' · ')}</small></div><button className="button secondary" onClick={() => loadPreset(x.playerIds)}>Load</button></div>) : <p className="muted">Save a recommended five to reuse it later.</p>}</section><section className="saved-card"><h3>Complete game plans</h3>{store.plans.length ? store.plans.map(x => <div className="saved-item" key={x.id}><div><b>{x.name}</b><small>{x.shifts.length} shifts · {new Date(x.createdAt).toLocaleDateString()}</small></div><button className="button secondary" onClick={() => { update(s => ({...s, game: x.settings})); setTab('lineups'); }}>Open</button></div>) : <p className="muted">Save a full rotation after building lineups.</p>}</section></div></section>}
    </div>
    {draft && <PlayerDialog player={draft} setPlayer={setDraft} onClose={() => setDraft(null)} onSave={savePlayer} onDelete={() => removePlayer(draft.id)} exists={store.players.some(p=>p.id===draft.id)}/>} {saveDialog && <NameDialog type={saveDialog} value={saveName} setValue={setSaveName} onClose={() => setSaveDialog(null)} onSave={commitSave}/>} 
  </main>;
}

function Setting({ label, value, options, onChange }: { label: string; value: string; options: string[][]; onChange: (v:string) => void }) { return <div className="setting"><span>{label}</span><div>{options.map(([v,label]) => <Chip key={v} active={v === value} onClick={() => onChange(v)}>{label}</Chip>)}</div></div>; }
function PlayerDialog({ player, setPlayer, onClose, onSave, onDelete, exists }: { player: Player; setPlayer:(p:Player)=>void; onClose:()=>void; onSave:()=>void; onDelete:()=>void; exists:boolean }) {
  function setRating(group: keyof Ratings, key: string, value: number) { const ratings = copy(player.ratings) as any; ratings[group][key] = value; const roles = player.roles.length ? player.roles : suggestedRoles(ratings); setPlayer({ ...player, ratings, roles, archetype: suggestArchetype(ratings, roles) }); }
  function toggleRole(role: Role) { const roles = player.roles.includes(role) ? player.roles.filter(x=>x!==role) : [...player.roles,role]; setPlayer({ ...player, roles, archetype: suggestArchetype(player.ratings, roles) }); }
  return <div className="dialog-backdrop"><div className="dialog"><div className="dialog-head"><div><p className="eyebrow ink">PLAYER PROFILE</p><h2>{exists ? 'Edit player' : 'New player'}</h2></div><button className="icon" onClick={onClose}>×</button></div><div className="form-grid"><label>Player name<input autoFocus value={player.name} onChange={e=>setPlayer({...player,name:e.target.value})} placeholder="e.g. Jordan Lee"/></label><label>Jersey #<input value={player.jerseyNumber || ''} onChange={e=>setPlayer({...player,jerseyNumber:e.target.value})} placeholder="3"/></label><label>Height <input value={player.height || ''} onChange={e=>setPlayer({...player,height:e.target.value})} placeholder="6′1″"/></label></div><div className="form-section"><span className="form-label">Position coverage</span><div className="chips">{POSITIONS.map(pos => <Chip key={pos} active={player.positions.includes(pos)} onClick={()=>setPlayer({...player,positions:player.positions.includes(pos)?player.positions.filter(x=>x!==pos):[...player.positions,pos]})}>{pos}</Chip>)}</div></div><div className="rating-key"><b>Scout on a 1–10 scale</b><span>1 major weakness · 3 limited · 5 capable · 7 strong · 9 elite · 10 defining strength</span></div>{bands.map(([group,label,tone,items]) => <section className={`rating-band ${tone}`} key={group}><h3>{label}</h3>{items.map(([key,label]) => { const value = (player.ratings[group as keyof Ratings] as any)[key]; return <label className="rating" key={key}><span>{label}<small>{ratingWords[value]}</small></span><input type="range" min="1" max="10" value={value} onChange={e=>setRating(group as keyof Ratings,key,+e.target.value)}/><b>{value}</b></label>; })}</section>)}<div className="form-section"><span className="form-label">Structured roles <small>Suggested from ratings; edit for real-world context.</small></span><div className="chips">{ROLES.map(role => <Chip key={role} active={player.roles.includes(role)} onClick={()=>toggleRole(role)}>{roleLabel(role)}</Chip>)}</div></div><label className="wide-label">Suggested archetype <input value={player.archetype} onChange={e=>setPlayer({...player,archetype:e.target.value})}/></label><label className="wide-label">Coach notes <textarea value={player.coachNotes || ''} onChange={e=>setPlayer({...player,coachNotes:e.target.value})} placeholder="Optional context that ratings cannot capture."/></label><div className="dialog-actions">{exists ? <button className="button danger" onClick={onDelete}>Delete player</button> : <span/>}<div><button className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" onClick={onSave}>Save player</button></div></div></div></div>;
}
function NameDialog({ type, value, setValue, onClose, onSave }: { type:'preset'|'plan'; value:string; setValue:(v:string)=>void; onClose:()=>void; onSave:()=>void }) { return <div className="dialog-backdrop"><div className="dialog small"><p className="eyebrow ink">SAVE TO PLAYBOOK</p><h2>{type === 'preset' ? 'Name this five' : 'Name this game plan'}</h2><p className="muted">{type === 'preset' ? 'This saves the current recommended five as a reusable preset.' : 'This saves the starter, every shift, and the current settings.'}</p><input autoFocus value={value} onChange={e=>setValue(e.target.value)} placeholder={type === 'preset' ? 'e.g. Shooting unit' : 'e.g. Thursday league game'}/><div className="dialog-actions"><span/><div><button className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={!value.trim()} onClick={onSave}>Save</button></div></div></div></div>; }
